# Generated by Django 2.0 on 2021-05-01 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210501_0811'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
